[theme]
primaryColor = "#1d9bf0"  # Twitter blue
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F5"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 10  # MB

[browser]
gatherUsageStats = false 